### ISSUE TITLE
Non parseable transactions in specific blocks

### ISSUE THREAD

**Issue by darklow** [yungwine/pytoniq#23]
We've been running block scanner for a few months now and we first time encountered issues with specific blocks. None of the blocks on mainnet from `37719962` to `37719966` are parseable and all fail with following error. Starting with block `37719967` all works again. Any ideas how to fix? Thank you.
```py
$ python blockscanner.py 37719962

Traceback (most recent call last):
  File "/Users/user/www/project/ton/blockscanner.py", line 246, in <module>
    asyncio.run(main())
  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/user/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/user/www/project/ton/blockscanner.py", line 240, in main
    await BlockScanner(
  File "/Users/user/www/project/ton/blockscanner.py", line 63, in run
    await self.block_handler(self.blks_queue.get_nowait(), self)
  File "/Users/user/www/project/ton/blockscanner.py", line 198, in handle_block
    transactions = await client.raw_get_block_transactions_ext(block)
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq/liteclient/client.py", line 756, in raw_get_block_transactions_ext
    transactions = parse_transactions(result)
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq/liteclient/client.py", line 739, in parse_transactions
    transaction = Transaction.deserialize(tr_root.begin_parse())
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/tlb/transaction.py", line 119, in deserialize
    out_msgs = ref.load_dict(15, value_deserializer=lambda src: MessageAny.deserialize(src.load_ref().begin_parse()))
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/boc/slice.py", line 222, in load_dict
    return HashMap.parse(self.load_ref().begin_parse(), key_length, key_deserializer, value_deserializer)
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/boc/hashmap/hashmap.py", line 123, in parse
    result = {key_deserializer(i): value_deserializer(j) for i, j in dict_result.items()}
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/boc/hashmap/hashmap.py", line 123, in <dictcomp>
    result = {key_deserializer(i): value_deserializer(j) for i, j in dict_result.items()}
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/tlb/transaction.py", line 119, in <lambda>
    out_msgs = ref.load_dict(15, value_deserializer=lambda src: MessageAny.deserialize(src.load_ref().begin_parse()))
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/tlb/transaction.py", line 188, in deserialize
    init = StateInit.deserialize(cell_slice)
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/tlb/account.py", line 270, in deserialize
    code=cell_slice.load_ref() if cell_slice.load_bit() else None,
  File "/Users/user/www/project/ton/.venv/lib/python3.9/site-packages/pytoniq_core/boc/slice.py", line 172, in load_ref
    ref = self.refs[self.ref_offset]
IndexError: list index out of range
```

**Comment by yungwine** [comment]
Fixed in `pytoniq-core` version 0.1.33. To update use command

```bash
pip install pytoniq-core -U
```
