### ISSUE TITLE
Get method "seqno" for account returned exit code -256

### ISSUE THREAD

**Issue by andreykanava** [yungwine/pytoniq#30]
Hello. Every time I am trying to make transfer I am getting this error. My code:

```
from dedust import Asset, Factory, PoolType, SwapParams, VaultNative
from pytoniq import WalletV4R2, LiteBalancer
import asyncio
import time

mnemonics = ""

async def main():
    provider = LiteBalancer.from_mainnet_config(2)
    await provider.start_up()

    wallet = await WalletV4R2.from_mnemonic(provider=provider, mnemonics=mnemonics)

    SCALE_ADDRESS = "EQBlqsm144Dq6SjbPI4jjZvA1hqTIP3CvHovbIfW_t-SCALE"

    TON = Asset.native()
    SCALE = Asset.jetton(SCALE_ADDRESS)

    pool = await Factory.get_pool(pool_type=PoolType.VOLATILE,
                                  assets=[TON, SCALE],
                                  provider=provider)

    swap_params = SwapParams(deadline=int(time.time() + 60 * 5),
                             recipient_address=wallet.address)
    swap_amount = int(float(input("Enter swap amount: ")) * 1e9)

    swap = VaultNative.create_swap_payload(amount=swap_amount,
                                           pool_address=pool.address,
                                           swap_params=swap_params)

    swap_amount = int(swap_amount + (0.25 * 1e9))  # 0.25 = gas_value

    await wallet.transfer(destination="EQDa4VOnTYlLvDJ0gZjNYm5PXfSmmtL6Vs6A_CZEtXCNICq_",  # native vault
                          amount=swap_amount,
                          body=swap)



asyncio.run(main())

```

Traceback:

```
Traceback (most recent call last):
  File "/root/sniper-bot/test_requests.py", line 46, in <module>
    asyncio.run(main())
  File "/root/.pyenv/versions/3.10.14/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.pyenv/versions/3.10.14/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/sniper-bot/test_requests.py", line 40, in main
    await wallet.transfer(destination="EQDa4VOnTYlLvDJ0gZjNYm5PXfSmmtL6Vs6A_CZEtXCNICq_",  # native vault
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/contract/wallets/wallet.py", line 143, in transfer
    return await self.raw_transfer(msgs=[wallet_message])
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/contract/wallets/wallet.py", line 131, in raw_transfer
    seqno = await self.get_seqno()
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/contract/wallets/wallet.py", line 157, in get_seqno
    return (await super().run_get_method('seqno'))[0]
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/contract/contract.py", line 111, in run_get_method
    return await self.provider.run_get_method(self.address, method, stack)
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/liteclient/balancer.py", line 359, in run_get_method
    return await self.execute_method('run_get_method', **self._get_args(locals())) 
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/liteclient/balancer.py", line 267, in execute_method
    resp = await peer_meth(*args, **kwargs)
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/liteclient/client.py", line 494, in run_get_method
    return await self.run_get_method_remote(address, method, stack, block)  # will be replaced with run_get_method_local in future
  File "/root/.pyenv/versions/sniper/lib/python3.10/site-packages/pytoniq/liteclient/client.py", line 526, in run_get_method_remote
    raise RunGetMethodError(address=address, method=method, exit_code=result['exit_code'])
pytoniq.liteclient.client.RunGetMethodError: Get method "seqno" for account Address<EQBqIGPRZfmOuk5o8CiqOOCVnpHIj7vx2_UF-REfLwc3znW-> returned exit code -256
```

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gkozyrev** [comment]
```
stonfi_swap.py:32: in swap_ton_to_jetton
    resp = loop.run_until_complete(wallet.transfer(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:653: in run_until_complete
    return future.result()
../../../.venv/lib/python3.11/site-packages/pytoniq/contract/wallets/wallet.py:143: in transfer
    return await self.raw_transfer(msgs=[wallet_message])
../../../.venv/lib/python3.11/site-packages/pytoniq/contract/wallets/wallet.py:131: in raw_transfer
    seqno = await self.get_seqno()
../../../.venv/lib/python3.11/site-packages/pytoniq/contract/wallets/wallet.py:157: in get_seqno
    return (await super().run_get_method('seqno'))[0]
../../../.venv/lib/python3.11/site-packages/pytoniq/contract/contract.py:111: in run_get_method
    return await self.provider.run_get_method(self.address, method, stack)
../../../.venv/lib/python3.11/site-packages/pytoniq/liteclient/balancer.py:345: in run_get_method
    return await self.execute_method('run_get_method', **self._get_args(locals()))
../../../.venv/lib/python3.11/site-packages/pytoniq/liteclient/balancer.py:263: in execute_method
    resp = await peer_meth(*args, **kwargs)
../../../.venv/lib/python3.11/site-packages/pytoniq/liteclient/client.py:477: in run_get_method
    return await self.run_get_method_remote(address, method, stack, block)  # will be replaced with run_get_method_local in future
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pytoniq.liteclient.client.LiteClient object at 0x10e9eae50>
address = Address<EQAGEuRvWk03zyfLH266bBpm7x4Uqm4X1z4v8VCQos_HToRM>
method = 'seqno', stack = <Cell 24[000000] -> 0 refs>
block = <TL BlockIdExt [wc=-1, shard=-9223372036854775808, seqno=39973985, root_hash=d64572886f635e79ae1b8cb0a41105d742050160519195d0d16cf3d1d86a08cc, file_hash=00f23b13ba0e25805f18dc199ea6ea64d1ffdeb81787bd7813d0e6068f1ce500] >

    async def run_get_method_remote(self, address: typing.Union[Address, str],
                                    method: typing.Union[int, str], stack: list,
                                    block: BlockIdExt = None
                                    ) -> list:
        if self.trust_level <= 1:
            self.logger.warning('remote get method result is not provable, use run_get_method_local for local tvm execution')
        mode = 7  # 111
        if block is None:
            block = self.last_mc_block
    
        if isinstance(address, str):
            address = Address(address)
        account = address.to_tl_account_id()
    
        if isinstance(method, str):
            method_id = (int.from_bytes(crc16(method.encode()), byteorder='big') & 0xffff) | 0x10000
        elif isinstance(method, int):
            method_id = method
        else:
            raise LiteClientError('provided method in unknown form')
    
        if isinstance(stack, list):
            stack = VmStack.serialize(stack)
        else:
            raise LiteClientError('provided stack in unknown form')
    
        data = {'mode': mode, 'id': block.to_dict(), 'account': account, 'method_id': method_id, 'params': stack.to_boc()}
        result = await self.liteserver_request('runSmcMethod', data)
    
        if result['exit_code'] != 0:
>           raise RunGetMethodError(address=address, method=method, exit_code=result['exit_code'])
E           pytoniq.liteclient.client.RunGetMethodError: Get method "seqno" for account Address<EQAGEuRvWk03zyfLH266bBpm7x4Uqm4X1z4v8VCQos_HToRM> returned exit code -256

../../../.venv/lib/python3.11/site-packages/pytoniq/liteclient/client.py:509: RunGetMethodError
```

Same problem

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bantalon** [comment]
Happened to me too when the source account already had positive TON balance but was in uninitialized state.
The state can be seen in an exploprer, [Tonviewer](https://tonviewer.com/) for example.
I performed a single transfer from an external wallet in order to initialize the account.
This made the account state to change from uninitialized to active.
After that getting the `seqno` worked as expected.

It would be good to improve the code to show a clearer error message in case of uninitialized accounts. 
It would be even bette to make the Pythoniq library be able to initialize account upon need.
