### ISSUE TITLE
Error processing block in raw_get_block method

### ISSUE THREAD

**Issue by Hazepusik** [yungwine/pytoniq#37]
I have an issue processing some workchain blocks using method raw_get_block: got `pytoniq_core.tlb.transaction.TransactionError: MsgEnvelope deserialization error tag: 5` exception.

Env:
 - python3.9
 - pytoniq==0.1.39
 - pytoniq-core==0.1.36

Source code for reproduction:
```python
import asyncio

from pytoniq import LiteClient
from pytoniq_core import BlockIdExt


async def run():
    client = LiteClient.from_mainnet_config(ls_i=0, trust_level=2)
    await client.connect()

    # Error block example
    block_json = {'workchain': 0, 'shard': 1152921504606846976, 'seqno': 45298633,
                  'root_hash': 'ff8111a62d7b9e8bf5ec6ca93a9b48a03ae0f451ea72a3b689dd61d61a8f92d9',
                  'file_hash': 'a92ec504a1850649f4a1f32e19c3d4f08424b1547cd7f28aa587c8b0b549e459'}

    # Working block example
    # block_json = {'workchain': 0, 'shard': 1152921504606846976, 'seqno': 45298616,
    # 'root_hash': '5af5dfb8258088a7e1f5d8ed8f6675376b902895f20c2bb013bc573a7bb50d02', 'file_hash':
    # 'de7469ebe4a8624ad34b482665884f4d9abce877e74f42b000c2db39a6f1f145'}

    block: BlockIdExt = BlockIdExt.from_dict(block_json)
    _ = await client.raw_get_block(block)
    print(f'Node block {block} ok')

if __name__ == '__main__':
    asyncio.run(run())
```

Exception:
```
Traceback (most recent call last):
  File "/Users/user/Library/issue.py", line 22, in run
    _ = await client.raw_get_block(block)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytoniq/liteclient/client.py", line 442, in raw_get_block
    return Block.deserialize(result_block.begin_parse())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytoniq_core/tlb/block.py", line 44, in deserialize
    extra = BlockExtra.deserialize(cell_slice.load_ref().begin_parse())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytoniq_core/tlb/block.py", line 840, in deserialize
    in_msg_descr = cell_slice.load_ref().begin_parse().load_hashmap_aug_e(256, x_deserializer=InMsg.deserialize, y_deserializer=ImportFees.deserialize)


...

    deserialize_hashmap_aug_node(slice, m, ret_dict, extras, prefix.copy(), x_deserializer, y_deserializer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytoniq_core/boc/hashmap/parse.py", line 80, in deserialize_hashmap_aug_node
    ret_dict[prefix.to01()] = x_deserializer(cs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytoniq_core/tlb/transaction.py", line 1152, in deserialize
    in_msg=MsgEnvelope.deserialize(cell_slice.load_ref().begin_parse()),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytoniq_core/tlb/transaction.py", line 1086, in deserialize
    raise TransactionError(f'MsgEnvelope deserialization error tag: {tag}')
pytoniq_core.tlb.transaction.TransactionError: MsgEnvelope deserialization error tag: 5
```

Any ideas how to fix it?

**Comment by yungwine** [comment]
Hi! This issue is fixed in `pytoniq_core` 0.1.37
